### ISSUE TITLE
Couchbase version

### ISSUE THREAD

**Issue by fijemax** [acaprojects/couchbase-orm#5]
Hello,
I try to use couchbase-orm.
I have some question to run it.
Which is the version couchbase this library is based ? And how configure couchbase bucket and user.
Best Regards
Maxime

**Comment by stakach** [comment]
Sorry I missed this - have been on holiday.
This has been tested against version 3 of couchbase and above.

I am planning on implementing sub-document editing for updates so it'll soon only work on the newer versions.

To generate the config on a new rails project run the command `rails generate couchbase_orm:config` and then you can configure connection settings there. Otherwise the tests also describe a lot of the functionality
