### ISSUE TITLE
Compatibility with modern version

### ISSUE THREAD

**Issue by MrRezaque** [acaprojects/couchbase-orm#6]
Can we make it compatible with the modern version of couchbase?
For now, I encountered that views don't work for couchbase 4.x and 5.x out of the box. It fails with `{"error":"not_found","reason":"Design document _design/funnel not found"}` 

If you lost interest in maintaining it, I could/would like to contribute and figure it myself, but at least can you please make CI config work correctly and fail because of test issues, not because of deps? I guess you as the creator can make it much faster than a complete stranger like me.

Thanks, Yar
/cc @stakach

**Comment by stakach** [comment]
Most of the active development goes into https://github.com/cotag/libcouchbase/ and that's working great with couchbase 5.

The reason for your issue is because views are only checked to be up to date at initialisation time
https://github.com/acaprojects/couchbase-orm/blob/master/lib/couchbase-orm/railtie.rb#L89

However when running rails in development mode the models are lazy loaded - meaning they are not picked up by this code. So there should be no issues in production.

I turn on `config.eager_load = true` in the development environment, which ensures all the code is loaded on boot

**Comment by stakach** [comment]
That said you are right that views take a while to spin up on couchbase 5 - so pushing an update to take that into account. We're only using couchbase 4 in production.

**Comment by stakach** [comment]
Just pushed libcouchbase (1.2.2) which ensures the couchbase-orm tests pass with couchbase 5
I would still turn on `config.eager_load = true`

I'm also enabling travis for this project however it is having issues at the moment

**Comment by stakach** [comment]
Pushed couchbase-orm 1.1.0
